# Generated by Django 2.1.4 on 2020-02-27 10:06

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='avatar/default.jpg', upload_to='avatar/', verbose_name='头像'),
        ),
    ]
