# Generated by Django 2.1.4 on 2020-02-27 10:27

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200227_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='avatar/default.jpg', upload_to='avatar/%Y/%m/%d', verbose_name='头像'),
        ),
    ]
