# Generated by Django 2.1.4 on 2020-01-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='desc', max_length=50),
        ),
    ]
