# Generated by Django 2.1.4 on 2020-01-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='total_num',
            field=models.IntegerField(default=0),
        ),
    ]
